version: "3"

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "chmod 755 /app/bin/initial_deploy.sh &&
             sh -c /app/bin/initial_deploy.sh &&
             python manage.py await_for_db &&
             python manage.py migrate &&
             gunicorn krzysztofbrzozowski.wsgi:application --bind 0.0.0.0:8000"

    environment:
      - VIRTUAL_HOST=localhost
      - DB_HOST=db
      - DB_NAME=db
      - DB_USER=postgres
      - DB_PASS=postgres
      - PRODUCTION=false
      - DO_INITIAL_DEPLOY=true

      # Env variables for initial deploy
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SUPERUSER_EMAIL=admin@admin.com

    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./db-data:/var/lib/postgresql/data 
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  nginx:
    depends_on:
      - app
    restart: always
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      # - "443:443"
    volumes:
      - /etc/nginx/conf.d

  dockergen:
    image: nginxproxy/docker-gen
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl
      /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl