name: Deploy

on:
    workflow_run:
        # Job depends on succesfull run of tests
        workflows: ["Tests"]
        types: [completed]
        

jobs:
    on-success:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps:
          - run: echo "First workflow was a success"
          - name: executing remote ssh commands using password
            uses: appleboy/ssh-action@v1.0.3
            with:
                host:       ${{ secrets.HOST }}
                username:   ${{ secrets.USERNAME }}
                password:   ${{ secrets.PASSWORD }}
                port:       ${{ secrets.PORT }}
                script: |
                    whoami
                    ls -al
                    [ ! -d "/home/${{ secrets.USERNAME }}/dest_dir" ] && git clone git@github.com:krzysztofbrzozowski/krzysztofbrzozowski_website.git dest_dir
                    cd dest_dir
                    git reset --hard && git checkout master && git pull origin master
                    docker compose -f "docker-compose.yml" up -d --build

   
    on-failure:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        steps:
            - run: echo "First workflow was a failure"
